using System.Collections.Generic;

namespace Baioss.Record.Application.Localization;

/// <summary>
/// Catálogo de textos de la interfaz, un diccionario por idioma.
///
/// <para><b>Reglas al añadir una cadena:</b> (1) añádela SIEMPRE en los dos diccionarios —hay un test que
/// falla si falta en alguno—; (2) el ESPAÑOL es el idioma de origen y el respaldo; (3) los marcadores
/// <c>{0}</c>, <c>{1}</c>… deben ser los mismos y significar lo mismo en ambos idiomas (también hay test);
/// (4) los mensajes de REGISTRO (Serilog) NO se traducen: son para soporte, no para el cliente.</para>
///
/// <para>Las claves llevan prefijo por zona (<c>Main_</c>, <c>Ch_</c>, <c>Lic_</c>…) para poder localizarlas
/// de un vistazo desde el XAML.</para>
/// </summary>
public static class Strings
{
    public static readonly IReadOnlyDictionary<string, string> Spanish = new Dictionary<string, string>
    {
        // --- Comunes ---
        ["Common_Close"] = "Cerrar",
        ["Common_Cancel"] = "Cancelar",
        ["Common_Save"] = "Guardar",
        ["Common_Accept"] = "Aceptar",
        ["Common_Apply"] = "Aplicar",
        ["Common_Browse"] = "Examinar…",
        ["Common_Edit"] = "Editar",
        ["Common_Delete"] = "Eliminar",
        ["Common_Refresh"] = "Actualizar",
        ["Common_Channel"] = "Canal",
        ["Common_None"] = "—",

        // --- Ventana principal ---
        ["Main_Title"] = "Baioss Record",
        ["Main_Subtitle_One"] = "· grabación broadcast de {0} canal",
        ["Main_Subtitle_Many"] = "· grabación broadcast de {0} canales",
        ["Main_Btn_License"] = "🔑 Licencia",
        ["Main_Btn_Settings"] = "🛠 Configuración",
        ["Main_Btn_Storage"] = "🗄 Almacenamiento",
        ["Main_Btn_Recordings"] = "🗂 Grabaciones",
        ["Main_Btn_Inputs"] = "🎛 Entradas",
        ["Main_Btn_Schedule"] = "🕒 Programación",
        ["Main_Btn_Presets"] = "⚙ Presets de grabación",
        ["Main_StorageBanner_Critical"] = "⚠  Almacenamiento crítico  —  queda muy poco espacio en el volumen de grabación",
        ["Main_Storage_Tooltip_One"] = "Almacenamiento del volumen de grabación",
        ["Main_Storage_Tooltip_Many"] = "Almacenamiento de los discos de grabación",
        ["Main_Storage_Measuring"] = "Almacenamiento de los discos de grabación (midiendo…)",
        ["Main_Storage_FreeUsed"] = "{0} libres · {1}%",
        ["Main_Storage_VolumeLine"] = "{0}: {1} libres de {2} ({3}% ocupado)",
        ["Main_Storage_TooltipMulti"] = "Discos de grabación (peor primero · {0} discos):",
        ["Main_Storage_TooltipSingle"] = "Volumen de grabación: {0} libres de {1} ({2}% ocupado)",
        ["Main_Banner_Emergency"] = "⚠  ALMACENAMIENTO EN EMERGENCIA  —  libera espacio para seguir grabando con normalidad",
        ["Main_Banner_Emergency_Multi"] = "⚠  ALMACENAMIENTO EN EMERGENCIA en {0}  —  libera espacio para seguir grabando en ese disco",
        ["Main_Banner_Critical_Multi"] = "⚠  Almacenamiento crítico en {0}  —  queda muy poco espacio en ese disco",

        // --- Panel de canal ---
        ["Ch_Name_A"] = "Canal Principal",
        ["Ch_Name_B"] = "Canal Secundario",
        ["Ch_Name_Other"] = "Canal {0}",
        ["Ch_FpsOut"] = "FPS OUT",
        ["Ch_Bitrate"] = "BITRATE",
        ["Ch_Dropped"] = "DROPPED",
        ["Ch_State"] = "ESTADO",
        ["Ch_Disk"] = "DISCO",
        ["Ch_Pgm"] = "PGM",
        ["Ch_Rec"] = "REC",
        ["Ch_Clip"] = "CLIP",
        ["Ch_AudioDbfs"] = "AUDIO dBFS",
        ["Ch_Record"] = "● Grabar",
        ["Ch_Stop"] = "■ Detener",
        ["Ch_SkipScheduled"] = "⏏ Detener grabación automática",
        ["Ch_ShowSchedule"] = "🕒 Mostrar programación",
        ["Ch_NoRecordingInProgress"] = "Sin grabación en curso",
        ["Ch_Running"] = "EN CURSO",
        ["Ch_Signal_Ok"] = "SEÑAL OK",
        ["Ch_Signal_Unstable"] = "INESTABLE",
        ["Ch_Signal_None"] = "SIN SEÑAL",
        ["Ch_Audio_Mono"] = "1 canal",
        ["Ch_Audio_Stereo"] = "2 canales",
        ["Ch_Audio_51"] = "6 canales",
        ["Ch_Audio_71"] = "8 canales",
        ["Ch_NoAudio"] = "Sin audio",
        ["Ch_DiskFree"] = "{0} libres",
        ["Ch_NativeResolution"] = "nativa",
        ["Ch_Profile_AudioOnly"] = "Solo audio · {0} · {1}",
        ["Ch_OutputFolderDialog"] = "Carpeta de destino de las grabaciones",
        ["Ch_DefaultRecordingName"] = "Grabación {0}",
        ["Ch_TodayEmpty"] = "Sin grabaciones programadas hoy",
        ["Ch_TodayNext"] = "Hoy no hay. Próxima: {0} · {1}",

        // --- Estados de grabación ---
        ["State_Idle"] = "Inactivo",
        ["State_Starting"] = "Iniciando",
        ["State_Recording"] = "Grabando",
        ["State_Paused"] = "Pausado",
        ["State_Stopping"] = "Deteniendo",

        // --- Alarmas ---
        ["Alarm_SignalLoss"] = "Sin señal de entrada",
        ["Alarm_VideoBlack"] = "Imagen en negro",
        ["Alarm_VideoFreeze"] = "Imagen congelada",
        ["Alarm_AudioSilence"] = "Silencio de audio",
        ["Alarm_DiskLow"] = "Espacio en disco bajo",
        ["Alarm_DiskCritical"] = "Disco casi lleno",
        ["Alarm_DiskEmergency"] = "Almacenamiento en EMERGENCIA — libera espacio ya",
        ["Alarm_Slate"] = "Sin señal — grabando carta de ajuste",
        ["Alarm_EncoderFallback"] = "Codificador por GPU no disponible — grabando con codificador alternativo",
        ["Alarm_FramesDropped"] = "Frames perdidos — el equipo no da abasto (CPU/GPU/disco)",
        ["Alarm_RecordingUnverified"] = "Grabación sin verificar — el archivo podría estar dañado",

        // --- Nombre de la grabación ---
        ["RecName_Title"] = "Nombre de la grabación",
        ["RecName_Header"] = "NOMBRE DE LA GRABACIÓN",
        ["RecName_Hint"] = "Si ya existe un archivo con ese nombre, se añadirá 1, 2, 3… al final para no chocar.",

        // --- Configuración general ---
        ["Cfg_Title"] = "Configuración general",
        ["Cfg_Header"] = "CONFIGURACIÓN GENERAL",
        ["Cfg_Subtitle"] = "Carpeta de destino y carta de ajuste por canal. El formato y la codificación se eligen en «⚙ Presets de grabación».",
        ["Cfg_OutputFolder"] = "CARPETA DE DESTINO",
        ["Cfg_SlateOnSignalLoss"] = "Carta de ajuste al perder señal (sigue grabando barras)",
        ["Cfg_Language"] = "IDIOMA",
        ["Cfg_Language_Hint"] = "Se aplica al instante. Por defecto se usa el idioma de Windows.",
        ["Cfg_Language_Spanish"] = "Español",
        ["Cfg_Language_English"] = "Inglés",

        // --- Entradas ---
        ["In_Title"] = "Entradas de los canales",
        ["In_Header"] = "ENTRADAS DE LOS CANALES",
        ["In_Subtitle"] = "Asigna una tarjeta DeckLink (SDI) o una cámara/capturadora DirectShow a cada canal.",
        ["In_Detect"] = "🔍 Detectar dispositivos",
        ["In_VideoInput"] = "ENTRADA DE VÍDEO",
        ["In_Audio"] = "AUDIO (DirectShow)",
        ["In_Format"] = "MODO / FORMATO (DeckLink)",
        ["In_Active"] = "Activa: {0}",
        ["In_Footer"] = "Al aplicar, el canal se reconstruye en caliente (suelta la fuente anterior y abre la nueva). Nota: un dispositivo en vivo no se puede abrir por dos procesos a la vez; grabar y previsualizar la misma entrada física a la vez requerirá un único proceso de captura (pendiente).",
        ["In_NdiTrademark"] = "NDI® es una marca registrada de Vizrt NDI AB.",
        ["In_Msg_PressDetect"] = "Pulsa «Detectar» para buscar tarjetas DeckLink y cámaras/capturadoras DirectShow.",
        ["In_Msg_Simulated"] = "Modo simulado (sin FFmpeg): la asignación de entradas no está disponible.",
        ["In_Msg_NoModes"] = " · DeckLink: no se detectaron modos (cierra cualquier captura que use la tarjeta y reintenta; revisa logs).",
        ["In_Msg_NothingFound"] = "No se detectaron tarjetas ni cámaras. (¿Drivers DeckLink instalados? ¿cámara conectada?)",
        ["In_Msg_Found"] = "{0} entrada(s) de vídeo y {1} de audio detectadas.",
        ["In_Msg_PickVideo"] = "Canal {0}: elige una entrada de vídeo.",
        ["In_Msg_Applying"] = "Aplicando «{0}» al Canal {1}…",
        ["In_Msg_Detecting"] = "Detectando dispositivos…",
        ["In_Msg_DetectError"] = "Error al detectar: {0}",
        ["In_Msg_NotAvailableSimulated"] = "No disponible en modo de demostración.",
        ["In_Msg_Applied"] = "Canal {0} → {1}{2}.",
        ["In_Msg_ApplyError"] = "Error al aplicar en Canal {0}: {1}",

        // --- Reasignación de entrada (mensajes que acaban en la ventana de Entradas) ---
        ["Rebind_Err_Simulated"] = "La reasignación de entrada no está disponible (modo de demostración).",
        ["Rebind_Err_Recording"] = "Detén la grabación antes de cambiar la entrada del canal.",
        ["Rebind_Err_Busy"] = "«{0}» ya está asignada al Canal {1}. Un dispositivo de captura no admite dos canales a la vez.",
        ["Rebind_Err_Timeout"] = "La entrada «{0}» no respondió en {1} s; se restauró la entrada anterior del Canal {2}.",

        // --- Licencia ---
        ["Lic_Title"] = "Licencia",
        ["Lic_Header"] = "LICENCIA",
        ["Lic_Subtitle"] = "Estado de la licencia de este equipo y activación.",
        ["Lic_State"] = "ESTADO",
        ["Lic_MachineCode"] = "CÓDIGO DE ESTE EQUIPO",
        ["Lic_MachineCode_Hint"] = "Envía este código a tu proveedor para que te emita la licencia. La licencia solo funcionará en este equipo.",
        ["Lic_Copy"] = "Copiar",
        ["Lic_Activate"] = "Activar",
        ["Lic_ActivateHeader"] = "ACTIVAR LICENCIA",
        ["Lic_Summary_Licensed"] = "Licencia activa",
        ["Lic_Summary_LicensedChannels_One"] = "Licencia activa · {0} canal",
        ["Lic_Summary_LicensedChannels_Many"] = "Licencia activa · {0} canales",
        ["Lic_Summary_TrialLastDay"] = "Prueba: último día",
        ["Lic_Summary_TrialDays"] = "Prueba: {0} días restantes",
        ["Lic_Summary_Unknown"] = "Licencia: no verificable",
        ["Lic_Summary_Expired"] = "Periodo de prueba terminado",
        ["Lic_Detail_Licensed"] = "Este equipo tiene una licencia permanente. No caduca.",
        ["Lic_Detail_LicensedChannels_One"] = "Este equipo tiene una licencia permanente de {0} canal. No caduca. Para ampliar canales, pide una licencia nueva a tu proveedor.",
        ["Lic_Detail_LicensedChannels_Many"] = "Este equipo tiene una licencia permanente de {0} canales. No caduca. Para ampliar canales, pide una licencia nueva a tu proveedor.",
        ["Lic_Detail_Trial"] = "Puedes usar todas las funciones durante el periodo de prueba. Cuando termine podrás seguir viendo las entradas, pero no iniciar grabaciones nuevas.",
        ["Lic_Detail_Expired"] = "El periodo de prueba ha terminado. Las grabaciones en curso NO se interrumpen, pero no se pueden iniciar nuevas hasta activar la licencia.",
        ["Lic_Detail_Unknown"] = "No se pudo comprobar el estado de la licencia. La grabación sigue disponible; revisa el registro de la aplicación.",
        ["Lic_Msg_Copied"] = "Código de equipo copiado. Envíaselo a tu proveedor para recibir la licencia.",
        ["Lic_Msg_CopyFailed"] = "No se pudo copiar automáticamente; selecciona el código y cópialo a mano.",
        ["Lic_Msg_Activated"] = "Licencia activada. Gracias.",
        ["Lic_Msg_Malformed"] = "La licencia no tiene un formato válido. Cópiala completa, tal como te la enviaron.",
        ["Lic_Msg_OtherMachine"] = "Esta licencia no es válida para este equipo. Comprueba que el código de equipo coincide con el que enviaste.",
        ["Lic_Msg_UnsupportedVersion"] = "Esta licencia requiere una versión más reciente de Baioss Record.",
        ["Lic_Msg_Invalid"] = "La licencia no es válida.",
        ["Lic_Msg_ActivateFailed"] = "No se pudo activar la licencia. Revisa que esté copiada completa.",
        ["Lic_Msg_NotSaved"] = "La licencia es válida, pero no se pudo guardar en este equipo. Revisa los permisos de «{0}» y vuelve a intentarlo.",
        ["Lic_Restart_Title"] = "Licencia activada",
        ["Lic_Restart_Body"] = "Licencia activada{0}. Gracias.\n\nLa aplicación se reiniciará ahora para aplicar los canales de tu licencia. Si hay alguna grabación en curso, se finalizará correctamente antes de cerrar.",
        ["Lic_Restart_Channels_One"] = " de {0} canal",
        ["Lic_Restart_Channels_Many"] = " de {0} canales",
        ["Lic_Blocked"] = "El periodo de prueba ha terminado. Activa la licencia para volver a grabar (código de equipo: {0}).",

        // --- Programación (ventana del canal) ---
        ["Sch_Ch_Title"] = "Programación",
        ["Sch_Ch_WindowTitle"] = "Programación de hoy · Canal {0}",
        ["Sch_Ch_HeaderToday"] = "PROGRAMACIÓN DE HOY · CANAL {0}",
        ["RecName_WindowTitle"] = "Guardar grabación — Canal {0}",
        ["RecName_Subtitle"] = "Canal {0} · ponle nombre para guardarla",
        ["Ch_Err_StartTitle"] = "No se pudo iniciar la grabación",
        ["Ch_Err_StopTitle"] = "No se pudo detener/renombrar la grabación",
        ["Sch_Ch_Subtitle"] = "Grabaciones programadas de hoy en este canal.",
        ["Sch_Ch_Empty"] = "No hay grabaciones programadas hoy en este canal.",
        ["Sch_In"] = "ENTRADA",
        ["Sch_Out"] = "SALIDA",
        ["Sch_Segment"] = "SEGMENTO",
        ["Sch_Title_Col"] = "TÍTULO",

        // --- Programación (ventana global) ---
        ["Sch_Title"] = "Programación de grabaciones",
        ["Sch_Header"] = "PROGRAMACIÓN DE GRABACIONES",
        ["Sch_Subtitle"] = "Graba automáticamente a la hora indicada, una vez o de forma recurrente. Usa el perfil activo del canal.",
        ["Sch_Today"] = "HOY",
        ["Sch_TodayEmpty"] = "No hay grabaciones programadas para hoy.",
        ["Sch_Channel"] = "CANAL",
        ["Sch_Repeat"] = "REPETICIÓN",
        ["Sch_Date"] = "FECHA",
        ["Sch_Days"] = "DÍAS",
        ["Sch_Next"] = "PRÓXIMA",
        ["Sch_StartTime"] = "HORA INICIO (hh:mm:ss)",
        ["Sch_EndTime"] = "HORA FIN (hh:mm:ss)",
        ["Sch_SegmentEvery"] = "Segmentar cada",
        ["Sch_SegmentHint"] = "min  (cada archivo queda completo; si se corrompe uno, no pierdes toda la grabación)",
        ["Sch_Import"] = "⬆ Importar",
        ["Sch_Export"] = "⬇ Exportar",
        ["Sch_Refresh"] = "🔄 Actualizar",
        ["Sch_ImportTooltip"] = "Importa una programación desde un archivo JSON exportado (añade las tareas).",
        ["Sch_ExportTooltip"] = "Exporta toda la programación a CSV (Excel) o JSON (copia de seguridad).",
        ["Sch_Day_Mon"] = "L",
        ["Sch_Day_Tue"] = "M",
        ["Sch_Day_Wed"] = "X",
        ["Sch_Day_Thu"] = "J",
        ["Sch_Day_Fri"] = "V",
        ["Sch_Day_Sat"] = "S",
        ["Sch_Day_Sun"] = "D",
        // Formulario y mensajes de la programación
        ["Sch_Rec_Once"] = "Una vez",
        ["Sch_Rec_Daily"] = "Cada día",
        ["Sch_Rec_Weekly"] = "Días de la semana",
        ["Sch_DefaultTitle"] = "Grabación programada",
        ["Sch_Form_New"] = "NUEVA PROGRAMACIÓN",
        ["Sch_Form_Edit"] = "EDITAR PROGRAMACIÓN",
        ["Sch_Note_Duration"] = "⏱ Duración: {0}.",
        ["Sch_Note_EndsNextDay"] = "⏭ La hora de fin es anterior a la de inicio: termina al día siguiente.",
        ["Sch_Note_SegmentsTooBig"] = "⚠ Los segmentos son ≥ que la grabación: será un solo archivo.",
        ["Sch_Dlg_ExportTitle"] = "Exportar programación de grabaciones",
        ["Sch_Dlg_ImportTitle"] = "Importar programación de grabaciones",
        ["Sch_Dlg_JsonFilter"] = "JSON de programación (*.json)|*.json|Todos los archivos (*.*)|*.*",
        ["Sch_Msg_Exported"] = "Programación exportada ({0}) a «{1}».",
        ["Sch_Msg_ExportFailed"] = "No se pudo exportar la programación: {0}",
        ["Sch_Msg_ImportedNothing"] = "No se importó nada: ",
        ["Sch_Msg_SkippedDup"] = "{0} con título ya existente",
        ["Sch_Msg_Imported"] = "Importadas {0} programación(es)",
        ["Sch_Msg_Skipped"] = " · omitidas: ",
        ["Sch_Msg_Count"] = "{0} programación(es). El scheduler corre mientras la app esté abierta.",
        ["Sch_Msg_NoJobs"] = "No hay grabaciones programadas. Crea una abajo.",
        ["Sch_Err_PickRecurrence"] = "Elige el tipo de repetición.",
        ["Sch_Err_PickWeekday"] = "Elige al menos un día de la semana.",
        ["Sch_Err_PastDate"] = "Esa fecha/hora ya pasó; elige una futura.",
        ["Sch_Err_DurationOverlaps"] = "La duración ({0}) alcanza la siguiente ocurrencia ({1}). Redúcela o cambia la repetición.",
        ["Sch_Err_DuplicateTitle"] = "Ya existe una grabación programada llamada «{0}». Elige otro nombre.",
        ["Sch_Err_Clash"] = "Choca con «{0}» en el Canal {1}. Ajusta la hora o la duración.",
        ["Sch_Note_SegmentsSingleFile"] = "los segmentos son ≥ que la grabación (un solo archivo)",
        ["Sch_Note_EndsNextDayAt"] = "termina al día siguiente a las {0}",
        ["Sch_Msg_Saved"] = "{0} «{1}» en Canal {2}.",
        ["Sch_Saved_Updated"] = "Actualizada",
        ["Sch_Saved_Scheduled"] = "Programada",
        ["Sch_Msg_Editing"] = "Editando «{0}». Cambia lo necesario y pulsa «Guardar cambios».",
        ["Sch_Msg_EditCancelled"] = "Edición cancelada.",
        ["Sch_Interval_Daily"] = "cada día",
        ["Sch_Interval_Days"] = "cada {0} días",
        ["Sch_Desc_Minutes"] = " · {0} min",
        ["Sch_Desc_Segments"] = " · segmentos {0} min",
        ["Sch_Desc_Once"] = "Una vez · {0} {1}",
        ["Sch_Desc_Daily"] = "Cada día · {0}",
        ["Sch_Desc_Weekly"] = "{0} · {1}",
        ["Sch_Desc_EndsNextDay"] = " · termina {0} del día sig.",
        ["Sch_EveryDay"] = "Todos los días",
        ["Sch_ChannelLabel"] = "Canal {0}",
        ["Sch_Pause"] = "Pausar",
        ["Sch_Resume"] = "Reanudar",
        ["Sch_SaveChanges"] = "💾 Guardar cambios",
        ["Sch_Add"] = "＋ Programar",
        ["Sch_St_Skipped"] = "Saltada",
        ["Sch_St_Scheduled"] = "Programada",
        ["Sch_St_Recorded"] = "Grabada",
        ["Sch_St_Running"] = "En curso",
        ["Sch_Notice"] = "  Aviso: ",
        ["Sch_Interval_Hours"] = "cada {0} h",

        // --- Almacenamiento ---
        ["Sto_Title"] = "Almacenamiento",
        ["Sto_Header"] = "ALMACENAMIENTO",
        ["Sto_Subtitle"] = "Retención automática, alertas por espacio y modo emergencia. Los cambios se aplican sin reiniciar. Seguro por defecto: nada se borra a menos que actives la retención o la auto-limpieza.",
        ["Sto_RetentionHeader"] = "RETENCIÓN AUTOMÁTICA",
        ["Sto_RetentionEnable"] = "Activar retención automática (borra/archiva grabaciones antiguas)",
        ["Sto_KeepDays"] = "Conservar (días, 0 = no borrar por días)",
        ["Sto_KeepFreePercent"] = "Mantener libre al menos (%, 0 = off)",
        ["Sto_KeepFreeGb"] = "Mantener libre al menos (GB, 0 = off)",
        ["Sto_IntervalMinutes"] = "Revisar cada (minutos, mín. 5)",
        ["Sto_ArchiveInstead"] = "Archivar en otra carpeta en vez de borrar",
        ["Sto_AlertsHeader"] = "ALERTAS POR ESPACIO Y MODO EMERGENCIA",
        ["Sto_WarnPercent"] = "Aviso (% ocupado, ámbar)",
        ["Sto_CriticalPercent"] = "Crítico (% ocupado)",
        ["Sto_EmergencyPercent"] = "Emergencia (% ocupado)",
        ["Sto_ThresholdsHint"] = "Los umbrales se ordenan solos: aviso ≤ crítico ≤ emergencia. 0 desactiva un umbral.",
        ["Sto_AutoCleanup"] = "Auto-limpiar al entrar en emergencia (borra lo NO protegido más antiguo)",
        ["Sto_BlockNew"] = "Bloquear el inicio de nuevas grabaciones durante la emergencia",
        ["Sto_Msg_NeedArchiveFolder"] = "⚠ Indica una carpeta de archivado, o desmarca «Archivar en otra carpeta».",
        ["Sto_Msg_SavedAdjusted"] = "✔ Guardado. Algunos valores se ajustaron al rango válido (aviso ≤ crítico ≤ emergencia · mín. 5 min · % 0–100).",
        ["Sto_Msg_Saved"] = "✔ Ajustes guardados y aplicados (los servicios los usarán en su próximo ciclo).",

        // --- Grabaciones (mensajes) ---
        ["Rec_Range_7"] = "Últimos 7 días",
        ["Rec_Range_30"] = "Últimos 30 días",
        ["Rec_Range_90"] = "Últimos 90 días",
        ["Rec_Range_365"] = "Último año",
        ["Rec_Summary_One"] = "{0} grabación · {1} · {2} protegida(s)",
        ["Rec_Summary_Many"] = "{0} grabaciones · {1} · {2} protegida(s)",
        ["Rec_Msg_Gone"] = "La grabación ya no existe (¿la borró la limpieza?). Actualiza la lista.",
        ["Rec_Msg_ProtectionFailed"] = "No se pudo cambiar la protección: {0}",

        // --- Presets (mensajes) ---
        ["Pre_Native"] = "nativa",
        ["Pre_Max"] = " (máx {0})",
        ["Pre_Yes"] = "sí",
        ["Pre_No"] = "no",
        ["Pre_SourceFps"] = "fuente",
        ["Pre_Cat_All"] = "Todos",
        ["Pre_Cat_Favorites"] = "★ Favoritos",
        ["Pre_Lbl_Container"] = "Contenedor:",
        ["Pre_Lbl_AudioOnly"] = "Solo audio:",
        ["Pre_Lbl_VideoCodec"] = "Códec vídeo:",
        ["Pre_Lbl_Resolution"] = "Resolución:",
        ["Pre_Lbl_Fps"] = "FPS:",
        ["Pre_Lbl_Bitrate"] = "Bitrate:",
        ["Pre_Lbl_Gop"] = "GOP:",
        ["Pre_Lbl_PixelFormat"] = "Pixel format:",
        ["Pre_Lbl_Scan"] = "Escaneo:",
        ["Pre_Lbl_RateControl"] = "Control tasa:",
        ["Pre_Lbl_AudioSection"] = "— Audio —",
        ["Pre_Lbl_AudioCodec"] = "Códec:",
        ["Pre_Lbl_AudioChannels"] = "Canales:",
        ["Pre_Lbl_SampleRate"] = "Sample rate:",
        ["Pre_Lbl_AudioBitrate"] = "Bitrate audio:",
        ["Pre_Confirm_Delete"] = "¿Eliminar el preset '{0}'?",
        ["Pre_Confirm_Title"] = "Confirmar",
        ["Pre_Msg_CannotApply"] = "El Canal {0} no admite aplicar el preset ahora (¿grabando o no configurable?).",

        // --- Grabaciones ---
        ["Rec_Title"] = "Grabaciones",
        ["Rec_Header"] = "GRABACIONES",
        ["Rec_Subtitle"] = "Historial de grabaciones. Marca las importantes como «Protegida» o «Importante» para EXCLUIRLAS de la limpieza automática.",
        ["Rec_Date"] = "FECHA",
        ["Rec_Time"] = "HORA",
        ["Rec_Channel"] = "CANAL",
        ["Rec_Name"] = "NOMBRE",
        ["Rec_Duration"] = "DURACIÓN",
        ["Rec_Size"] = "TAMAÑO",
        ["Rec_Operator"] = "OPERADOR",
        ["Rec_Protection"] = "PROTECCIÓN",
        ["Rec_Actions"] = "ACCIONES",
        ["Rec_Empty"] = "No hay grabaciones en el rango seleccionado.",
        ["Rec_Refresh"] = "↻ Actualizar",
        ["Rec_Protect"] = "🔒 Proteger",
        ["Rec_Important"] = "★ Importante",
        ["Rec_Normal"] = "○ Normal",
        ["Rec_OpenFolder"] = "Abrir la carpeta de la grabación",
        ["Rec_Tip_Protect"] = "Excluir siempre de la limpieza automática",
        ["Rec_Tip_Important"] = "Marcar como importante (también se excluye de la limpieza)",
        ["Rec_Tip_Normal"] = "Quitar la protección (vuelve a entrar en la limpieza automática)",

        // --- Presets ---
        ["Pre_Title"] = "Presets de grabación / encoding",
        ["Pre_Formats"] = "FORMATOS",
        ["Pre_Presets"] = "PRESETS",
        ["Pre_Factory"] = "fábrica",
        ["Pre_CommandLine"] = "Línea de comandos FFmpeg",
        ["Pre_ApplyTo"] = "Aplicar a:",
        ["Pre_ApplyToChannel"] = "Aplicar al canal",
        ["Pre_New"] = "＋ Nuevo",
        ["Pre_Edit"] = "✎ Editar",
        ["Pre_Duplicate"] = "⧉ Duplicar",
        ["Pre_Delete"] = "🗑 Eliminar",
        ["Pre_Import"] = "⭱ Importar",
        ["Pre_Export"] = "⭳ Exportar",

        // --- Editor de preset ---
        ["PreEd_Title"] = "Editar preset",
        ["PreEd_Header"] = "Configuración del preset",
        ["PreEd_Name"] = "Nombre",
        ["PreEd_Category"] = "Categoría",
        ["PreEd_Description"] = "Descripción",
        ["PreEd_VideoCodec"] = "Códec video",
        ["PreEd_AudioCodec"] = "Códec audio",
        ["PreEd_Container"] = "Contenedor",
        ["PreEd_Bitrate"] = "Bitrate (Mbps)",
        ["PreEd_MaxBitrate"] = "Max bitrate (Mbps)",
        ["PreEd_RateControl"] = "Control de tasa",
        ["PreEd_Quality"] = "Calidad (CRF/CQ)",
        ["PreEd_Width"] = "Ancho (0=nativo)",
        ["PreEd_Height"] = "Alto (0=nativo)",
        ["PreEd_Fps"] = "FPS (0=fuente)",
        ["PreEd_Gop"] = "GOP",
        ["PreEd_Scan"] = "Escaneo",
        ["PreEd_PixelFormat"] = "Pixel format",
        ["PreEd_IntraProfile"] = "Perfil intra",
        ["PreEd_IntraHint"] = "(solo ProRes / DNxHR)",
        ["PreEd_AudioChannels"] = "Canales",
        ["PreEd_AudioOnly"] = "Solo audio",

        // --- Diálogos de la aplicación ---
        ["Dlg_Close_Title"] = "Cerrar Baioss Record",
        ["Dlg_Close_Question"] = "¿Seguro que quieres cerrar Baioss Record?",
        ["Dlg_Close_Recording"] = "Hay {0} grabación(es) en curso (canal {1}).\n\n¿Detenerlas y salir? Se finalizarán los archivos correctamente antes de cerrar.",
        ["Dlg_Closing_Title"] = "Baioss Record — cerrando…",
        ["Dlg_Restarting_Title"] = "Baioss Record — reiniciando para aplicar la licencia…",
        ["Dlg_AlreadyRunning"] = "Baioss Record ya está en ejecución.",
        ["Dlg_StartFailed"] = "No se pudo iniciar Baioss Record:\n{0}",
        ["Dlg_Ffmpeg_Title"] = "Baioss Record — falta FFmpeg",
        ["Dlg_Ffmpeg_Body"] = "Falta FFmpeg, que es el motor de grabación.\n\nBaioss Record funciona en modo de demostración y NO podrá grabar hasta que lo instales.\n\nCopia «ffmpeg.exe» y «ffprobe.exe» en esta carpeta:\n{0}\n\nTienes las instrucciones en el archivo FFMPEG-LEEME.txt de esa misma carpeta.",
    };

    public static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        // --- Common ---
        ["Common_Close"] = "Close",
        ["Common_Cancel"] = "Cancel",
        ["Common_Save"] = "Save",
        ["Common_Accept"] = "OK",
        ["Common_Apply"] = "Apply",
        ["Common_Browse"] = "Browse…",
        ["Common_Edit"] = "Edit",
        ["Common_Delete"] = "Delete",
        ["Common_Refresh"] = "Refresh",
        ["Common_Channel"] = "Channel",
        ["Common_None"] = "—",

        // --- Main window ---
        ["Main_Title"] = "Baioss Record",
        ["Main_Subtitle_One"] = "· broadcast recording, {0} channel",
        ["Main_Subtitle_Many"] = "· broadcast recording, {0} channels",
        ["Main_Btn_License"] = "🔑 License",
        ["Main_Btn_Settings"] = "🛠 Settings",
        ["Main_Btn_Storage"] = "🗄 Storage",
        ["Main_Btn_Recordings"] = "🗂 Recordings",
        ["Main_Btn_Inputs"] = "🎛 Inputs",
        ["Main_Btn_Schedule"] = "🕒 Schedule",
        ["Main_Btn_Presets"] = "⚙ Recording presets",
        ["Main_StorageBanner_Critical"] = "⚠  Storage critical  —  very little space left on the recording volume",
        ["Main_Storage_Tooltip_One"] = "Recording volume storage",
        ["Main_Storage_Tooltip_Many"] = "Recording disks storage",
        ["Main_Storage_Measuring"] = "Recording disks storage (measuring…)",
        ["Main_Storage_FreeUsed"] = "{0} free · {1}%",
        ["Main_Storage_VolumeLine"] = "{0}: {1} free of {2} ({3}% used)",
        ["Main_Storage_TooltipMulti"] = "Recording disks (worst first · {0} disks):",
        ["Main_Storage_TooltipSingle"] = "Recording volume: {0} free of {1} ({2}% used)",
        ["Main_Banner_Emergency"] = "⚠  STORAGE EMERGENCY  —  free up space to keep recording normally",
        ["Main_Banner_Emergency_Multi"] = "⚠  STORAGE EMERGENCY on {0}  —  free up space to keep recording on that disk",
        ["Main_Banner_Critical_Multi"] = "⚠  Storage critical on {0}  —  very little space left on that disk",

        // --- Channel panel ---
        ["Ch_Name_A"] = "Main Channel",
        ["Ch_Name_B"] = "Secondary Channel",
        ["Ch_Name_Other"] = "Channel {0}",
        ["Ch_FpsOut"] = "FPS OUT",
        ["Ch_Bitrate"] = "BITRATE",
        ["Ch_Dropped"] = "DROPPED",
        ["Ch_State"] = "STATUS",
        ["Ch_Disk"] = "DISK",
        ["Ch_Pgm"] = "PGM",
        ["Ch_Rec"] = "REC",
        ["Ch_Clip"] = "CLIP",
        ["Ch_AudioDbfs"] = "AUDIO dBFS",
        ["Ch_Record"] = "● Record",
        ["Ch_Stop"] = "■ Stop",
        ["Ch_SkipScheduled"] = "⏏ Stop scheduled recording",
        ["Ch_ShowSchedule"] = "🕒 Show schedule",
        ["Ch_NoRecordingInProgress"] = "No recording in progress",
        ["Ch_Running"] = "RUNNING",
        ["Ch_Signal_Ok"] = "SIGNAL OK",
        ["Ch_Signal_Unstable"] = "UNSTABLE",
        ["Ch_Signal_None"] = "NO SIGNAL",
        ["Ch_Audio_Mono"] = "1 channel",
        ["Ch_Audio_Stereo"] = "2 channels",
        ["Ch_Audio_51"] = "6 channels",
        ["Ch_Audio_71"] = "8 channels",
        ["Ch_NoAudio"] = "No audio",
        ["Ch_DiskFree"] = "{0} free",
        ["Ch_NativeResolution"] = "native",
        ["Ch_Profile_AudioOnly"] = "Audio only · {0} · {1}",
        ["Ch_OutputFolderDialog"] = "Destination folder for recordings",
        ["Ch_DefaultRecordingName"] = "Recording {0}",
        ["Ch_TodayEmpty"] = "No recordings scheduled today",
        ["Ch_TodayNext"] = "Nothing today. Next: {0} · {1}",

        // --- Recording states ---
        ["State_Idle"] = "Idle",
        ["State_Starting"] = "Starting",
        ["State_Recording"] = "Recording",
        ["State_Paused"] = "Paused",
        ["State_Stopping"] = "Stopping",

        // --- Alarms ---
        ["Alarm_SignalLoss"] = "No input signal",
        ["Alarm_VideoBlack"] = "Black picture",
        ["Alarm_VideoFreeze"] = "Frozen picture",
        ["Alarm_AudioSilence"] = "Audio silence",
        ["Alarm_DiskLow"] = "Low disk space",
        ["Alarm_DiskCritical"] = "Disk almost full",
        ["Alarm_DiskEmergency"] = "Storage EMERGENCY — free up space now",
        ["Alarm_Slate"] = "No signal — recording test pattern",
        ["Alarm_EncoderFallback"] = "GPU encoder unavailable — recording with a fallback encoder",
        ["Alarm_FramesDropped"] = "Dropped frames — the machine cannot keep up (CPU/GPU/disk)",
        ["Alarm_RecordingUnverified"] = "Unverified recording — the file may be damaged",

        // --- Recording name ---
        ["RecName_Title"] = "Recording name",
        ["RecName_Header"] = "RECORDING NAME",
        ["RecName_Hint"] = "If a file with that name already exists, 1, 2, 3… will be appended so nothing is overwritten.",

        // --- General settings ---
        ["Cfg_Title"] = "General settings",
        ["Cfg_Header"] = "GENERAL SETTINGS",
        ["Cfg_Subtitle"] = "Destination folder and test pattern per channel. Format and encoding are chosen in «⚙ Recording presets».",
        ["Cfg_OutputFolder"] = "DESTINATION FOLDER",
        ["Cfg_SlateOnSignalLoss"] = "Test pattern on signal loss (keeps recording bars)",
        ["Cfg_Language"] = "LANGUAGE",
        ["Cfg_Language_Hint"] = "Applied instantly. Windows' language is used by default.",
        ["Cfg_Language_Spanish"] = "Spanish",
        ["Cfg_Language_English"] = "English",

        // --- Inputs ---
        ["In_Title"] = "Channel inputs",
        ["In_Header"] = "CHANNEL INPUTS",
        ["In_Subtitle"] = "Assign a DeckLink (SDI) card or a DirectShow camera/capture device to each channel.",
        ["In_Detect"] = "🔍 Detect devices",
        ["In_VideoInput"] = "VIDEO INPUT",
        ["In_Audio"] = "AUDIO (DirectShow)",
        ["In_Format"] = "MODE / FORMAT (DeckLink)",
        ["In_Active"] = "Active: {0}",
        ["In_Footer"] = "On Apply, the channel is rebuilt live (it releases the previous source and opens the new one). Note: a live device cannot be opened by two processes at once; recording and previewing the same physical input simultaneously will require a single capture process (pending).",
        ["In_NdiTrademark"] = "NDI® is a registered trademark of Vizrt NDI AB.",
        ["In_Msg_PressDetect"] = "Press «Detect» to look for DeckLink cards and DirectShow cameras/capture devices.",
        ["In_Msg_Simulated"] = "Demonstration mode (no FFmpeg): assigning inputs is not available.",
        ["In_Msg_NoModes"] = " · DeckLink: no modes detected (close anything else using the card and retry; check the logs).",
        ["In_Msg_NothingFound"] = "No cards or cameras detected. (DeckLink drivers installed? Camera connected?)",
        ["In_Msg_Found"] = "{0} video input(s) and {1} audio input(s) detected.",
        ["In_Msg_PickVideo"] = "Channel {0}: choose a video input.",
        ["In_Msg_Applying"] = "Applying «{0}» to Channel {1}…",
        ["In_Msg_Detecting"] = "Detecting devices…",
        ["In_Msg_DetectError"] = "Detection failed: {0}",
        ["In_Msg_NotAvailableSimulated"] = "Not available in demonstration mode.",
        ["In_Msg_Applied"] = "Channel {0} → {1}{2}.",
        ["In_Msg_ApplyError"] = "Could not apply to Channel {0}: {1}",

        // --- Input rebinding (messages that end up in the Inputs window) ---
        ["Rebind_Err_Simulated"] = "Changing the input is not available (demonstration mode).",
        ["Rebind_Err_Recording"] = "Stop the recording before changing the channel's input.",
        ["Rebind_Err_Busy"] = "«{0}» is already assigned to Channel {1}. A capture device cannot serve two channels at once.",
        ["Rebind_Err_Timeout"] = "The input «{0}» did not respond within {1} s; Channel {2} was restored to its previous input.",

        // --- License ---
        ["Lic_Title"] = "License",
        ["Lic_Header"] = "LICENSE",
        ["Lic_Subtitle"] = "License status for this machine, and activation.",
        ["Lic_State"] = "STATUS",
        ["Lic_MachineCode"] = "THIS MACHINE'S CODE",
        ["Lic_MachineCode_Hint"] = "Send this code to your provider so they can issue your license. The license will only work on this machine.",
        ["Lic_Copy"] = "Copy",
        ["Lic_Activate"] = "Activate",
        ["Lic_ActivateHeader"] = "ACTIVATE LICENSE",
        ["Lic_Summary_Licensed"] = "License active",
        ["Lic_Summary_LicensedChannels_One"] = "License active · {0} channel",
        ["Lic_Summary_LicensedChannels_Many"] = "License active · {0} channels",
        ["Lic_Summary_TrialLastDay"] = "Trial: last day",
        ["Lic_Summary_TrialDays"] = "Trial: {0} days left",
        ["Lic_Summary_Unknown"] = "License: not verifiable",
        ["Lic_Summary_Expired"] = "Trial period ended",
        ["Lic_Detail_Licensed"] = "This machine has a permanent license. It does not expire.",
        ["Lic_Detail_LicensedChannels_One"] = "This machine has a permanent {0}-channel license. It does not expire. To add channels, request a new license from your provider.",
        ["Lic_Detail_LicensedChannels_Many"] = "This machine has a permanent {0}-channel license. It does not expire. To add channels, request a new license from your provider.",
        ["Lic_Detail_Trial"] = "You can use every feature during the trial period. When it ends you will still see the inputs, but you will not be able to start new recordings.",
        ["Lic_Detail_Expired"] = "The trial period has ended. Recordings already in progress are NOT interrupted, but no new ones can be started until you activate a license.",
        ["Lic_Detail_Unknown"] = "The license status could not be checked. Recording is still available; check the application log.",
        ["Lic_Msg_Copied"] = "Machine code copied. Send it to your provider to receive your license.",
        ["Lic_Msg_CopyFailed"] = "Could not copy automatically; select the code and copy it manually.",
        ["Lic_Msg_Activated"] = "License activated. Thank you.",
        ["Lic_Msg_Malformed"] = "The license format is not valid. Copy it in full, exactly as you received it.",
        ["Lic_Msg_OtherMachine"] = "This license is not valid for this machine. Check that the machine code matches the one you sent.",
        ["Lic_Msg_UnsupportedVersion"] = "This license requires a newer version of Baioss Record.",
        ["Lic_Msg_Invalid"] = "The license is not valid.",
        ["Lic_Msg_ActivateFailed"] = "The license could not be activated. Check that it was copied in full.",
        ["Lic_Msg_NotSaved"] = "The license is valid, but it could not be saved on this machine. Check the permissions of «{0}» and try again.",
        ["Lic_Restart_Title"] = "License activated",
        ["Lic_Restart_Body"] = "License activated{0}. Thank you.\n\nThe application will now restart to apply your license's channels. If a recording is in progress, it will be finalised correctly before closing.",
        ["Lic_Restart_Channels_One"] = ", {0} channel",
        ["Lic_Restart_Channels_Many"] = ", {0} channels",
        ["Lic_Blocked"] = "The trial period has ended. Activate your license to record again (machine code: {0}).",

        // --- Schedule (channel window) ---
        ["Sch_Ch_Title"] = "Schedule",
        ["Sch_Ch_WindowTitle"] = "Today's schedule · Channel {0}",
        ["Sch_Ch_HeaderToday"] = "TODAY'S SCHEDULE · CHANNEL {0}",
        ["RecName_WindowTitle"] = "Save recording — Channel {0}",
        ["RecName_Subtitle"] = "Channel {0} · give it a name to save it",
        ["Ch_Err_StartTitle"] = "The recording could not be started",
        ["Ch_Err_StopTitle"] = "The recording could not be stopped/renamed",
        ["Sch_Ch_Subtitle"] = "Today's scheduled recordings for this channel.",
        ["Sch_Ch_Empty"] = "No recordings scheduled today for this channel.",
        ["Sch_In"] = "START",
        ["Sch_Out"] = "END",
        ["Sch_Segment"] = "SEGMENT",
        ["Sch_Title_Col"] = "TITLE",

        // --- Schedule (global window) ---
        ["Sch_Title"] = "Recording schedule",
        ["Sch_Header"] = "RECORDING SCHEDULE",
        ["Sch_Subtitle"] = "Records automatically at the given time, once or repeatedly. Uses the channel's active profile.",
        ["Sch_Today"] = "TODAY",
        ["Sch_TodayEmpty"] = "No recordings scheduled for today.",
        ["Sch_Channel"] = "CHANNEL",
        ["Sch_Repeat"] = "REPEAT",
        ["Sch_Date"] = "DATE",
        ["Sch_Days"] = "DAYS",
        ["Sch_Next"] = "NEXT",
        ["Sch_StartTime"] = "START TIME (hh:mm:ss)",
        ["Sch_EndTime"] = "END TIME (hh:mm:ss)",
        ["Sch_SegmentEvery"] = "Split every",
        ["Sch_SegmentHint"] = "min  (each file is complete on its own; if one is damaged you don't lose the whole recording)",
        ["Sch_Import"] = "⬆ Import",
        ["Sch_Export"] = "⬇ Export",
        ["Sch_Refresh"] = "🔄 Refresh",
        ["Sch_ImportTooltip"] = "Imports a schedule from an exported JSON file (adds the tasks).",
        ["Sch_ExportTooltip"] = "Exports the whole schedule to CSV (Excel) or JSON (backup).",
        ["Sch_Day_Mon"] = "M",
        ["Sch_Day_Tue"] = "T",
        ["Sch_Day_Wed"] = "W",
        ["Sch_Day_Thu"] = "T",
        ["Sch_Day_Fri"] = "F",
        ["Sch_Day_Sat"] = "S",
        ["Sch_Day_Sun"] = "S",
        // Schedule form and messages
        ["Sch_Rec_Once"] = "Once",
        ["Sch_Rec_Daily"] = "Every day",
        ["Sch_Rec_Weekly"] = "Days of the week",
        ["Sch_DefaultTitle"] = "Scheduled recording",
        ["Sch_Form_New"] = "NEW SCHEDULE",
        ["Sch_Form_Edit"] = "EDIT SCHEDULE",
        ["Sch_Note_Duration"] = "⏱ Duration: {0}.",
        ["Sch_Note_EndsNextDay"] = "⏭ The end time is before the start time: it ends the next day.",
        ["Sch_Note_SegmentsTooBig"] = "⚠ Segments are ≥ the recording: it will be a single file.",
        ["Sch_Dlg_ExportTitle"] = "Export recording schedule",
        ["Sch_Dlg_ImportTitle"] = "Import recording schedule",
        ["Sch_Dlg_JsonFilter"] = "Schedule JSON (*.json)|*.json|All files (*.*)|*.*",
        ["Sch_Msg_Exported"] = "Schedule exported ({0}) to «{1}».",
        ["Sch_Msg_ExportFailed"] = "The schedule could not be exported: {0}",
        ["Sch_Msg_ImportedNothing"] = "Nothing was imported: ",
        ["Sch_Msg_SkippedDup"] = "{0} with an existing title",
        ["Sch_Msg_Imported"] = "{0} schedule(s) imported",
        ["Sch_Msg_Skipped"] = " · skipped: ",
        ["Sch_Msg_Count"] = "{0} schedule(s). The scheduler runs while the app is open.",
        ["Sch_Msg_NoJobs"] = "No scheduled recordings yet. Create one below.",
        ["Sch_Err_PickRecurrence"] = "Choose the repeat type.",
        ["Sch_Err_PickWeekday"] = "Choose at least one day of the week.",
        ["Sch_Err_PastDate"] = "That date/time has already passed; choose a future one.",
        ["Sch_Err_DurationOverlaps"] = "The duration ({0}) reaches the next occurrence ({1}). Shorten it or change the repeat.",
        ["Sch_Err_DuplicateTitle"] = "A scheduled recording named «{0}» already exists. Choose another name.",
        ["Sch_Err_Clash"] = "It clashes with «{0}» on Channel {1}. Adjust the time or the duration.",
        ["Sch_Note_SegmentsSingleFile"] = "segments are ≥ the recording (a single file)",
        ["Sch_Note_EndsNextDayAt"] = "ends the next day at {0}",
        ["Sch_Msg_Saved"] = "«{1}» {0} on Channel {2}.",
        ["Sch_Saved_Updated"] = "updated",
        ["Sch_Saved_Scheduled"] = "scheduled",
        ["Sch_Msg_Editing"] = "Editing «{0}». Change what you need and press «Save changes».",
        ["Sch_Msg_EditCancelled"] = "Editing cancelled.",
        ["Sch_Interval_Daily"] = "every day",
        ["Sch_Interval_Days"] = "every {0} days",
        ["Sch_Desc_Minutes"] = " · {0} min",
        ["Sch_Desc_Segments"] = " · {0} min segments",
        ["Sch_Desc_Once"] = "Once · {0} {1}",
        ["Sch_Desc_Daily"] = "Every day · {0}",
        ["Sch_Desc_Weekly"] = "{0} · {1}",
        ["Sch_Desc_EndsNextDay"] = " · ends {0} next day",
        ["Sch_EveryDay"] = "Every day",
        ["Sch_ChannelLabel"] = "Channel {0}",
        ["Sch_Pause"] = "Pause",
        ["Sch_Resume"] = "Resume",
        ["Sch_SaveChanges"] = "💾 Save changes",
        ["Sch_Add"] = "＋ Schedule",
        ["Sch_St_Skipped"] = "Skipped",
        ["Sch_St_Scheduled"] = "Scheduled",
        ["Sch_St_Recorded"] = "Recorded",
        ["Sch_St_Running"] = "Running",
        ["Sch_Notice"] = "  Note: ",
        ["Sch_Interval_Hours"] = "every {0} h",

        // --- Storage ---
        ["Sto_Title"] = "Storage",
        ["Sto_Header"] = "STORAGE",
        ["Sto_Subtitle"] = "Automatic retention, space alerts and emergency mode. Changes apply without restarting. Safe by default: nothing is deleted unless you enable retention or auto-cleanup.",
        ["Sto_RetentionHeader"] = "AUTOMATIC RETENTION",
        ["Sto_RetentionEnable"] = "Enable automatic retention (deletes/archives old recordings)",
        ["Sto_KeepDays"] = "Keep for (days, 0 = don't delete by age)",
        ["Sto_KeepFreePercent"] = "Keep at least free (%, 0 = off)",
        ["Sto_KeepFreeGb"] = "Keep at least free (GB, 0 = off)",
        ["Sto_IntervalMinutes"] = "Check every (minutes, min. 5)",
        ["Sto_ArchiveInstead"] = "Archive to another folder instead of deleting",
        ["Sto_AlertsHeader"] = "SPACE ALERTS AND EMERGENCY MODE",
        ["Sto_WarnPercent"] = "Warning (% used, amber)",
        ["Sto_CriticalPercent"] = "Critical (% used)",
        ["Sto_EmergencyPercent"] = "Emergency (% used)",
        ["Sto_ThresholdsHint"] = "Thresholds sort themselves: warning ≤ critical ≤ emergency. 0 disables a threshold.",
        ["Sto_AutoCleanup"] = "Auto-clean on entering emergency (deletes the oldest UNPROTECTED recordings)",
        ["Sto_BlockNew"] = "Block starting new recordings during the emergency",
        ["Sto_Msg_NeedArchiveFolder"] = "⚠ Choose an archive folder, or clear «Archive to another folder».",
        ["Sto_Msg_SavedAdjusted"] = "✔ Saved. Some values were adjusted to the valid range (warning ≤ critical ≤ emergency · min. 5 min · % 0–100).",
        ["Sto_Msg_Saved"] = "✔ Settings saved and applied (services will use them on their next cycle).",

        // --- Recordings (messages) ---
        ["Rec_Range_7"] = "Last 7 days",
        ["Rec_Range_30"] = "Last 30 days",
        ["Rec_Range_90"] = "Last 90 days",
        ["Rec_Range_365"] = "Last year",
        ["Rec_Summary_One"] = "{0} recording · {1} · {2} protected",
        ["Rec_Summary_Many"] = "{0} recordings · {1} · {2} protected",
        ["Rec_Msg_Gone"] = "That recording no longer exists (deleted by cleanup?). Refresh the list.",
        ["Rec_Msg_ProtectionFailed"] = "Could not change the protection: {0}",

        // --- Presets (messages) ---
        ["Pre_Native"] = "native",
        ["Pre_Max"] = " (max {0})",
        ["Pre_Yes"] = "yes",
        ["Pre_No"] = "no",
        ["Pre_SourceFps"] = "source",
        ["Pre_Cat_All"] = "All",
        ["Pre_Cat_Favorites"] = "★ Favourites",
        ["Pre_Lbl_Container"] = "Container:",
        ["Pre_Lbl_AudioOnly"] = "Audio only:",
        ["Pre_Lbl_VideoCodec"] = "Video codec:",
        ["Pre_Lbl_Resolution"] = "Resolution:",
        ["Pre_Lbl_Fps"] = "FPS:",
        ["Pre_Lbl_Bitrate"] = "Bitrate:",
        ["Pre_Lbl_Gop"] = "GOP:",
        ["Pre_Lbl_PixelFormat"] = "Pixel format:",
        ["Pre_Lbl_Scan"] = "Scan:",
        ["Pre_Lbl_RateControl"] = "Rate control:",
        ["Pre_Lbl_AudioSection"] = "— Audio —",
        ["Pre_Lbl_AudioCodec"] = "Codec:",
        ["Pre_Lbl_AudioChannels"] = "Channels:",
        ["Pre_Lbl_SampleRate"] = "Sample rate:",
        ["Pre_Lbl_AudioBitrate"] = "Audio bitrate:",
        ["Pre_Confirm_Delete"] = "Delete the preset '{0}'?",
        ["Pre_Confirm_Title"] = "Confirm",
        ["Pre_Msg_CannotApply"] = "Channel {0} cannot take the preset right now (recording, or not configurable?).",

        // --- Recordings ---
        ["Rec_Title"] = "Recordings",
        ["Rec_Header"] = "RECORDINGS",
        ["Rec_Subtitle"] = "Recording history. Mark the important ones as «Protected» or «Important» to EXCLUDE them from automatic cleanup.",
        ["Rec_Date"] = "DATE",
        ["Rec_Time"] = "TIME",
        ["Rec_Channel"] = "CHANNEL",
        ["Rec_Name"] = "NAME",
        ["Rec_Duration"] = "DURATION",
        ["Rec_Size"] = "SIZE",
        ["Rec_Operator"] = "OPERATOR",
        ["Rec_Protection"] = "PROTECTION",
        ["Rec_Actions"] = "ACTIONS",
        ["Rec_Empty"] = "No recordings in the selected range.",
        ["Rec_Refresh"] = "↻ Refresh",
        ["Rec_Protect"] = "🔒 Protect",
        ["Rec_Important"] = "★ Important",
        ["Rec_Normal"] = "○ Normal",
        ["Rec_OpenFolder"] = "Open the recording's folder",
        ["Rec_Tip_Protect"] = "Always exclude from automatic cleanup",
        ["Rec_Tip_Important"] = "Mark as important (also excluded from cleanup)",
        ["Rec_Tip_Normal"] = "Remove protection (goes back into automatic cleanup)",

        // --- Presets ---
        ["Pre_Title"] = "Recording / encoding presets",
        ["Pre_Formats"] = "FORMATS",
        ["Pre_Presets"] = "PRESETS",
        ["Pre_Factory"] = "factory",
        ["Pre_CommandLine"] = "FFmpeg command line",
        ["Pre_ApplyTo"] = "Apply to:",
        ["Pre_ApplyToChannel"] = "Apply to channel",
        ["Pre_New"] = "＋ New",
        ["Pre_Edit"] = "✎ Edit",
        ["Pre_Duplicate"] = "⧉ Duplicate",
        ["Pre_Delete"] = "🗑 Delete",
        ["Pre_Import"] = "⭱ Import",
        ["Pre_Export"] = "⭳ Export",

        // --- Preset editor ---
        ["PreEd_Title"] = "Edit preset",
        ["PreEd_Header"] = "Preset configuration",
        ["PreEd_Name"] = "Name",
        ["PreEd_Category"] = "Category",
        ["PreEd_Description"] = "Description",
        ["PreEd_VideoCodec"] = "Video codec",
        ["PreEd_AudioCodec"] = "Audio codec",
        ["PreEd_Container"] = "Container",
        ["PreEd_Bitrate"] = "Bitrate (Mbps)",
        ["PreEd_MaxBitrate"] = "Max bitrate (Mbps)",
        ["PreEd_RateControl"] = "Rate control",
        ["PreEd_Quality"] = "Quality (CRF/CQ)",
        ["PreEd_Width"] = "Width (0=native)",
        ["PreEd_Height"] = "Height (0=native)",
        ["PreEd_Fps"] = "FPS (0=source)",
        ["PreEd_Gop"] = "GOP",
        ["PreEd_Scan"] = "Scan",
        ["PreEd_PixelFormat"] = "Pixel format",
        ["PreEd_IntraProfile"] = "Intra profile",
        ["PreEd_IntraHint"] = "(ProRes / DNxHR only)",
        ["PreEd_AudioChannels"] = "Channels",
        ["PreEd_AudioOnly"] = "Audio only",

        // --- Application dialogs ---
        ["Dlg_Close_Title"] = "Close Baioss Record",
        ["Dlg_Close_Question"] = "Are you sure you want to close Baioss Record?",
        ["Dlg_Close_Recording"] = "There are {0} recording(s) in progress (channel {1}).\n\nStop them and exit? The files will be finalised correctly before closing.",
        ["Dlg_Closing_Title"] = "Baioss Record — closing…",
        ["Dlg_Restarting_Title"] = "Baioss Record — restarting to apply the license…",
        ["Dlg_AlreadyRunning"] = "Baioss Record is already running.",
        ["Dlg_StartFailed"] = "Baioss Record could not start:\n{0}",
        ["Dlg_Ffmpeg_Title"] = "Baioss Record — FFmpeg is missing",
        ["Dlg_Ffmpeg_Body"] = "FFmpeg is missing; it is the recording engine.\n\nBaioss Record runs in demonstration mode and will NOT be able to record until you install it.\n\nCopy ffmpeg.exe and ffprobe.exe into this folder:\n{0}\n\nInstructions are in the FFMPEG-README.txt file in that same folder.",
    };
}
